export const POLISH_MUNICIPALITIES: string[] = [
  "Aleksandrów Łódzki",
  "Augustów",
  "Bartoszyce",
  "Bełchatów",
  "Będzin",
  "Biała Podlaska",
  "Białogard",
  "Białystok",
  "Bielsko-Biała",
  "Biłgoraj",
  "Bochnia",
  "Bolesławiec",
  "Braniewo",
  "Brodnica",
  "Brzeg",
  "Brzesko",
  "Brzeziny",
  "Busko-Zdrój",
  "Bydgoszcz",
  "Bytom",
  "Bytów",
  "Chełm",
  "Chełmno",
  "Chojnice",
  "Chorzów",
  "Chrzanów",
  "Ciechanów",
  "Cieszyn",
  "Czarnków",
  "Częstochowa",
  "Człuchów",
  "Czeladź",
  "Darłowo",
  "Dąbrowa Górnicza",
  "Dąbrowa Tarnowska",
  "Dębica",
  "Dębno",
  "Działdowo",
  "Dzierżoniów",
  "Elbląg",
  "Ełk",
  "Garwolin",
  "Gdańsk",
  "Gdynia",
  "Giżycko",
  "Gliwice",
  "Głogów",
  "Głowno",
  "Głubczyce",
  "Gniezno",
  "Goleniów",
  "Golub-Dobrzyń",
  "Gorzów Wielkopolski",
  "Gostynin",
  "Gostyń",
  "Góra",
  "Grajewo",
  "Grodzisk Mazowiecki",
  "Grodzisk Wielkopolski",
  "Grójec",
  "Grudziądz",
  "Gryfice",
  "Gryfino",
  "Hajnówka",
  "Hrubieszów",
  "Iława",
  "Inowrocław",
  "Jarocin",
  "Jarosław",
  "Jasło",
  "Jastrzębie-Zdrój",
  "Jawor",
  "Jaworzno",
  "Jelenia Góra",
  "Jędrzejów",
  "Kalisz",
  "Kamienna Góra",
  "Kamień Pomorski",
  "Kartuzy",
  "Katowice",
  "Kazimierza Wielka",
  "Kępno",
  "Kętrzyn",
  "Kielce",
  "Kluczbork",
  "Kłobuck",
  "Kłodzko",
  "Koło",
  "Kołobrzeg",
  "Konin",
  "Końskie",
  "Koszalin",
  "Kościan",
  "Kościerzyna",
  "Kozienice",
  "Kraków",
  "Kraśnik",
  "Krosno",
  "Krosno Odrzańskie",
  "Krotoszyn",
  "Kutno",
  "Kwidzyn",
  "Legionowo",
  "Legnica",
  "Leszno",
  "Lębork",
  "Lidzbark Warmiński",
  "Limanowa",
  "Lipno",
  "Lipsko",
  "Lubaczów",
  "Luban",
  "Lubartów",
  "Lubawa",
  "Lubień Kujawski",
  "Lublin",
  "Lubliniec",
  "Luboń",
  "Lwówek Śląski",
  "Łańcut",
  "Łask",
  "Łęczyca",
  "Łobez",
  "Łomża",
  "Łowicz",
  "Łódź",
  "Łuków",
  "Maków Mazowiecki",
  "Malbork",
  "Małogoszcz",
  "Mielec",
  "Międzychód",
  "Międzyrzec Podlaski",
  "Międzyrzecz",
  "Mikołów",
  "Milanówek",
  "Mińsk Mazowiecki",
  "Mława",
  "Mogielnica",
  "Mogilno",
  "Mońki",
  "Mrągowo",
  "Mszana Dolna",
  "Mysłowice",
  "Myszków",
  "Myślenice",
  "Myślibórz",
  "Nakło nad Notecią",
  "Namysłów",
  "Nidzica",
  "Nisko",
  "Nowa Dęba",
  "Nowa Ruda",
  "Nowa Sól",
  "Nowe Miasto Lubawskie",
  "Nowy Dwór Gdański",
  "Nowy Dwór Mazowiecki",
  "Nowy Sącz",
  "Nowy Targ",
  "Nowy Tomyśl",
  "Nysa",
  "Oborniki",
  "Olecko",
  "Olesno",
  "Olkusz",
  "Olsztyn",
  "Olsztynek",
  "Oława",
  "Opoczno",
  "Opole",
  "Opole Lubelskie",
  "Ostrołęka",
  "Ostrowiec Świętokrzyski",
  "Ostrów Mazowiecka",
  "Ostrów Wielkopolski",
  "Ostrzeszów",
  "Oświęcim",
  "Otwock",
  "Pabianice",
  "Pajęczno",
  "Parczew",
  "Piaseczno",
  "Piekary Śląskie",
  "Piła",
  "Pińczów",
  "Piotrków Trybunalski",
  "Pisz",
  "Pleszew",
  "Płock",
  "Płońsk",
  "Poddębice",
  "Polkowice",
  "Połczyn-Zdrój",
  "Poniatowa",
  "Poznań",
  "Prabuty",
  "Proszowice",
  "Prudnik",
  "Pruszków",
  "Przasnysz",
  "Przemyśl",
  "Przeworsk",
  "Przysucha",
  "Pszczyna",
  "Puck",
  "Puławy",
  "Pułtusk",
  "Pyrzyce",
  "Raciąż",
  "Racibórz",
  "Radom",
  "Radomsko",
  "Radziejów",
  "Radzionków",
  "Radzyń Podlaski",
  "Rawicz",
  "Rawa Mazowiecka",
  "Ropczyce",
  "Ruda Śląska",
  "Rumia",
  "Rybnik",
  "Rypin",
  "Rzeszów",
  "Sandomierz",
  "Sanok",
  "Sejny",
  "Sępólno Krajeńskie",
  "Siedlce",
  "Siemianowice Śląskie",
  "Sieradz",
  "Sierpc",
  "Skarżysko-Kamienna",
  "Skierniewice",
  "Skoczów",
  "Słubice",
  "Słupca",
  "Słupsk",
  "Sochaczew",
  "Sokołów Podlaski",
  "Sokółka",
  "Sopot",
  "Sosnowiec",
  "Stalowa Wola",
  "Starachowice",
  "Stargard",
  "Starogard Gdański",
  "Staszów",
  "Strzelce Krajeńskie",
  "Strzelce Opolskie",
  "Strzelno",
  "Strzelin",
  "Sucha Beskidzka",
  "Suchowola",
  "Sulęcin",
  "Suwałki",
  "Swarzędz",
  "Syców",
  "Szamotuły",
  "Szczecin",
  "Szczecinek",
  "Szczytno",
  "Szprotawa",
  "Sztum",
  "Szubin",
  "Śrem",
  "Środa Wielkopolska",
  "Świdnica",
  "Świdnik",
  "Świdwin",
  "Świebodzice",
  "Świebodzin",
  "Świecie",
  "Świętochłowice",
  "Świnoujście",
  "Tarnobrzeg",
  "Tarnowskie Góry",
  "Tarnów",
  "Tczew",
  "Tomaszów Lubelski",
  "Tomaszów Mazowiecki",
  "Toruń",
  "Trzcianka",
  "Trzebinia",
  "Tuchola",
  "Turek",
  "Tuszyn",
  "Tychy",
  "Ustka",
  "Ustroń",
  "Wadowice",
  "Wałbrzych",
  "Wałcz",
  "Warszawa",
  "Wąbrzeźno",
  "Wągrówiec",
  "Węgorzewo",
  "Węgrów",
  "Wieliczka",
  "Wieluń",
  "Wieruszów",
  "Wisła",
  "Włocławek",
  "Włodawa",
  "Włoszczowa",
  "Wodzisław Śląski",
  "Wołomin",
  "Wołów",
  "Wrocław",
  "Wrzeszcz",
  "Września",
  "Wschowa",
  "Wyrzysk",
  "Wysokie Mazowieckie",
  "Wyszków",
  "Zabrze",
  "Zakopane",
  "Zambrów",
  "Zamość",
  "Zawiercie",
  "Ząbki",
  "Ząbkowice Śląskie",
  "Zduńska Wola",
  "Zgierz",
  "Zgorzelec",
  "Zielona Góra",
  "Złotoryja",
  "Złotów",
  "Zwoleń",
  "Żagań",
  "Żary",
  "Żnin",
  "Żory",
  "Żuromin",
  "Żyrardów",
  "Żywiec",
];